# =================================================================
#                   ░█▀▀░█▀▄░█▀▀░█▀▀░▀█▀░█▀▄
#                   ░█░█░█▀▄░█▀▀░█▀▀░░█░░█░█
#                   ░▀▀▀░▀░▀░▀▀▀░▀▀▀░░▀░░▀▀░
# =================================================================
# https://patorjk.com/software/taag/#p=display&f=Pagga&t=GREETD&x=none&v=4&h=4&w=80&we=false

[terminal]
vt = 1

[default_session]
command = "tuigreet --remember --time --cmd 'start-hyprland'"
user = "greeter"
